package org.example;

public enum Event {
    SOLVED_REQUEST,
    REJECTED_REQUEST,
    RECEIVED_REQUEST,
    ADMIN_RECEIVED_REQUESTS,
    ADDED_PRODUCTION_REVIEW,
    FAVORITE_PRODUCTION_REVIEW,
    RATED_PRODUCTION_REVIEW;
}
